shell = "nu -c '{}'"

[[items]]
name = "helix"
path = "https://github.com/tinted-theming/base16-helix"
themes-dir = "themes"
hook = """
let helix_dir = ($env.HOME | path join ".dotfiles/configuration/helix");
cp --force %f ($helix_dir | path join "themes/theme.toml");
let helix_config = ($helix_dir | path join "config.toml");
open $helix_config | upsert theme "theme" | save --force $helix_config
"""
