[[language]]
name = "css"
auto-format = true

[language.formatter]
command = "prettierd"
args = [".css"]

[[language]]
name = "haskell"
auto-format = true

[[language]]
name = "html"
auto-format = true

[language.formatter]
command = "prettierd"
args = [".html"]

[[language]]
name = "just"
auto-format = true

[language.formatter]
command = "just"
args = ["--justfile", "/dev/stdin", "--dump"]

[[language]]
name = "markdown"
auto-format = true

[language.formatter]
command = "prettierd"
args = [".md"]

[[language]]
name = "nix"
auto-format = true

[language.formatter]
command = "alejandra"

[[language]]
name = "scss"
auto-format = true

[language.formatter]
command = "prettierd"
args = [".scss"]

[[language]]
name = "toml"
auto-format = true

[language.formatter]
command = "taplo"
args = ["format", "-"]

[language-server.haskell-language-server.config]
formattingProvider = "fourmolu"
