[[language]]
name = "haskell"
auto-format = true

[language.formatter]
command = "alejandra"
args = ["format", "-"]

[[language]]
name = "haskell"
auto-format = true

[language.formatter]
command = "alejandra"

[[language]]
name = "just"
auto-format = true

[language.formatter]
command = "just"
args = ["--justfile", "/dev/stdin", "--dump"]

[[language]]
name = "nix"
auto-format = true

[language.formatter]
command = "alejandra"
args = [".md"]

[[language]]
name = "toml"
auto-format = true

[language.formatter]
command = "taplo"
args = ["format", "-"]

[language-server.haskell-language-server.config]
formattingProvider = "fourmolu"
